# Site settings
title: Markisha Berrien-Fitzsimons
email: markishab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
linkedin_username: mberrien-fitzsimons
twitter_username: MishaBerrien
github_username: mberrien-fitzsimons

# Build settings
markdown: kramdown
